name: Wisecow CI/CD

# Trigger workflow on push to main or PRs to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push Docker image
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mohammedirfan123/wisecow:latest 

      # Step 4: Install kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 5: Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # Step 6: Apply Kubernetes manifests (skip client-side validation)
      - name: Apply Kubernetes manifests (skip validation)
        run: |
          kubectl apply --validate=false -f wisecow-deployment.yml
          kubectl apply --validate=false -f wisecow-service.yml
          kubectl apply --validate=false -f wisecow-ingress.yml

      # Step 7: Wait for rollout (non-fatal)
      - name: Wait for deployment rollout (non-fatal)
        run: |
          kubectl rollout status deployment/wisecow-deployment || echo "Rollout check failed or cluster unreachable (ignored)"
